### PR TITLE
Added a simple example

### PR DESCRIPTION
**Pull request by JordyMoos**
With this PR i added a simple example usage of the notification module.

I also named your username `z_alepop` to fix dependency order in the final index.html when the project gets made.
This is a bit of a weird solution but without the z your module comes before the native scheduler and will then fail.

### CODE REVIEW

**Comment by alepop** [comment]
@JordyMoos thank you for your PR!!!
But I have an error when trying to run example code in your branch
```
Error: Your .elm/packages/ directory may be corrupted. I was led to believe that
z_alepop/elm-notification existed, but I could not find anything when I went to
look up the published versions of this package.
```

**Comment by JordyMoos** [comment]
@alepop good catch I will check it out

**Comment by JordyMoos** [comment]
Hey @alepop

If i do the following steps:
```
git clone https://github.com/JordyMoos/elm-notification.git
cd elm-notification/examples/simple/
elm-install
elm-reactor
```
And then goto `localhost:8000` and click on `Simple.elm` then it all works.

Can you try these steps too?

Edit:
Changed the git repo to the https url

**Comment by alepop** [comment]
@JordyMoos sorry, my mistake, I forgot to install `elm-github-install`. Everything fine, thanks for PR. Merge.

**Pull request merged**
